from . import crm_ai_config
from . import crm_ai_service
from . import crm_ai_call_session
from . import crm_ai_transcript_line
from . import crm_ai_document_checklist
from . import crm_customer_segment
from . import crm_account_contact
from . import crm_ai_document
from . import crm_product_recommendation
from . import crm_ai_coaching_report
from . import banking_profile
from . import corebanking_sync
from . import res_partner
from . import crm_lead
from . import mail_thread
