{
    'name': 'CRM AI Banking',
    'author': 'Custom Development',
    'version': '19.0.1.3.0',
    'category': 'Customer Relationship Management',
    'summary': 'AI-powered CRM for banking: realtime call transcription, email AI, document checklist, lead intelligence',
    'depends': ['crm', 'mail', 'base_automation', 'base'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/mail_activity_type_data.xml',
        'data/ir_cron_data.xml',
        'data/product_checklist_data.xml',
        'data/product_eligibility_data.xml',
        'data/customer_segment_data.xml',
        'views/crm_ai_config_views.xml',
        'views/crm_ai_call_session_views.xml',
        'views/crm_customer_segment_views.xml',
        'views/crm_account_contact_views.xml',
        'views/crm_ai_document_views.xml',
        'views/crm_product_recommendation_views.xml',
        'views/crm_ai_coaching_report_views.xml',
        'views/banking_profile_views.xml',
        'views/corebanking_sync_views.xml',
        'views/banking_profile_popup.xml',
        'views/crm_lead_views_inherit.xml',
        'views/crm_document_checklist_views.xml',
        'views/wizard_scan_document_views.xml',
        'views/wizard_zalo_compose_views.xml',
        'views/wizard_generate_proposal_views.xml',
        'views/res_partner_views_inherit.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'crm_ai_banking/static/src/css/crm_ai_banking.css',
            'crm_ai_banking/static/src/xml/ai_templates.xml',
            'crm_ai_banking/static/src/js/live_call_screen.js',
            'crm_ai_banking/static/src/js/twilio_call.js',
            'crm_ai_banking/static/src/js/ai_assistant_panel.js',
            'crm_ai_banking/static/src/js/camera_capture_widget.js',
            'crm_ai_banking/static/src/js/ai_copilot.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
